### ISSUE TITLE
Disable running tests in subprocesses?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testrunner#111]
### What I did:

I am running `coverage` against `zope.fanstatic`. This packages uses `layers` which are run in a subprocess.
`coverage` is (without some extra configuration which I wanted to avoid) not able to compute coverage for the tests run in the subprocess.
See https://github.com/zopefoundation/zope.fanstatic/pull/2 where most of `test_computeurl.py` is not covered but actually run (checked it with a `pdb`) because the layer runs in a sub process.  (Compare [coveralls.io](https://coveralls.io/builds/36635206/source?filename=src%2Fzope%2Ffanstatic%2Ftests%2Ftest_computeurl.py) for the result.)

### What I expect to happen:

I'd expect a command line switch so I could disable running tests on layers in subprocesses.

### What actually happened:

Maybe I overlooked something or there no easy way to achieve this: But I dir not find a way using the existing command line switches to disable using subprocesses.

### What version of Python and Zope/Addons I am using:

Using zope.testrunner 5.2 on Python 3.7.9

**Comment by mgedmin** [comment]
Subprocesses are used under two circumstances only:
- the user explicitly asks for parallelism by specifying a command line option (I'm guessing this is not the case here)
- there's a test layer that modifies global state but doesn't implement tearDown to undo its modifications, leaving a subprocess as the only way of ensuring a clean environment for subsequent test layers

You have two possible approaches for dealing with it:
1. modify the test layer to allow teardown (sometimes it's as simple as specifying allow_teardown=True, if you use zope.app.testing.functional, which I'm not sure anyone actually uses any more)
2. enable [subprocess coverage tracking](https://coverage.readthedocs.io/en/coverage-5.4/subprocess.html) (ZODB is a project that uses zope.testrunner's layers and also does this, via its [buildout.cfg](https://github.com/zopefoundation/ZODB/blob/0eae10cd0ee7ce4ab9d5bc109227f462f2eab4c9/buildout.cfg#L35-L41))

Ideally zope.testrunner would support coverage.py intergation natively (instead of its obsolete trace.py support) and ideally it would take care of everything, but that's work that somebody would need to volunteer to do.

**Comment by mgedmin** [comment]
I'm not sure if I should tag this as `invalid` or `wontfix`.  We don't have a label for `impossible`.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2021-1-27 05:50 -0800:
>I am running `coverage` against `zope.fanstatic`. This packages uses `layers` which are run in a subprocess.
>`coverage` is (without some extra configuration which I wanted to avoid) not able to compute coverage for the tests run in the subprocess.
>
>### What I expect to happen:
>
>I'd expect a command line switch so I could disable running tests on layers in subprocesses.

Usually, layer tests are not run in a subprocess.
This happens only when a layer has set up layer infrastructure
which cannot be dismantled safely. In this case, follow up tests
are executed in a new process (to get a clean state).

With this explanation, I think that your expectation cannot be fulfilled
without scrificing test independence.

**Comment by icemac** [comment]
Thank you for the explanation. Let's see what I can do in `zope.fanstatic` to increase measured coverage there.
