### ISSUE TITLE
Tests fail on 3.13a1

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testrunner#155]
The tests fail on Python 3.13a1, see
https://github.com/zopefoundation/zope.testrunner/actions/runs/6767286602/job/18389668025?pr=154

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2023-11-5 22:53 -0800:
>The tests fail on Python 3.13a1, see
>https://github.com/zopefoundation/zope.testrunner/actions/runs/6767286602/job/18389668025?pr=154

I have seen an issue report explaining Python 3.13 test related problems:
Python 3.13 strips (some) whitespace from "docstring"s potentially
with an effect to "doctest"s.

Hopefully, Python's `doctest` module will (eventually) come with a
normalizer making this whitespace removal transparent.
Otherwise, we likely would need to employ such a normalizer
(in many `zopefoundation` projects).

**Comment by dataflake** [comment]
The tests are now green, calling this resolved.
