### ISSUE TITLE
Test representation in summaries changed with Python 3.11+

### ISSUE THREAD

**Issue by fschulze** [zopefoundation/zope.testrunner#168]
The representation of test names changed with Python 3.11+ for test failure summaries etc.

With Python <= 3.10 it looks like this:
```
Tests with failures:
   test_stderr_failure (sample2.stdstreamstest.Test)
```

Starting with Python 3.11 it looks like this:
```
Tests with failures:
   test_stderr_failure (sample2.stdstreamstest.Test.test_stderr_failure)
```

The following commit adjusted the tests instead of fixing the output:
https://github.com/zopefoundation/zope.testrunner/commit/263fb77459c1ba6212fede417de08b56b6425e6a

I would be willing to look into fixing this, but first wanted to ask if this is desired and a PR would be accepted.

**Comment by icemac** [comment]
@fschulze Why do you see a problem with the new format? I adjusted the tests because the new format will stick for newer Python versions. When dropping support for Python 3.10 after October 2026 we can even replace the changes in https://github.com/zopefoundation/zope.testrunner/commit/263fb77459c1ba6212fede417de08b56b6425e6a with the new variant.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-5-5 23:36 -0700:
>@fschulze Why do you see a problem with the new format?

I find the new format better: the information in the `(...)` is now
precisely what `-t` regular expressions are applied to.
From my point of view this outweighs the slightly increased redundancy.

**Comment by fschulze** [comment]
Thanks for the feedback!
